name: 🐛 Bug
description: Report a bug or unexpected behavior in open-parse
labels: [bug, pending]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to open-parse! ✊

  - type: checkboxes
    id: version-checks
    attributes:
      label: Initial Checks
      description: Just making sure you're using the latest version
      options:
        - label: I confirm that I'm on the latest version
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. 🙏
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please add a self-contained,
        [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.

      placeholder: |
        import openparse

        ...
      render: Python

  - type: textarea
    id: version
    attributes:
      label: Python, open-parse & OS Version
      description: |
        Which version of Python & open-parse are you using, and which Operating System?

        Please run the following command and copy the output below:

        ```bash
        python -c "import openparse.version; print(openparse.version.version_info())"
        ```

      render: Text
    validations:
      required: true
